CREATE TABLE student (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    fname VARCHAR(30) NOT NULL,
    lname VARCHAR(30) NOT NULL,
    course VARCHAR(50) NOT NULL,
    contact VARCHAR(50) NOT NULL,
)